### ISSUE TITLE
trpc-maven-plugin下面的test方法报错

### ISSUE THREAD

**Issue by qq781261148** [trpc-group/trpc-java#28]
![image](https://github.com/trpc-group/trpc-java/assets/46473445/ee44fc79-1e37-45d1-b6dc-225ee4c122d7)

![image](https://github.com/trpc-group/trpc-java/assets/46473445/bf1f4a47-68a0-402a-bf57-09eb52eaef6a)
mojoDescriptors这个map只有
![image](https://github.com/trpc-group/trpc-java/assets/46473445/0a6584f7-0800-4861-9f04-2d30766eab57)
zhe'g这个插件下的4个mojo

**Comment by wardseptember** [comment]
@qq781261148 你的jdk是什么版本，jdk8才能执行单测的

**Comment by qq781261148** [comment]
@wardseptember 
![image](https://github.com/trpc-group/trpc-java/assets/46473445/7b4be561-9c24-478a-9336-4ee82c3aa31e)

**Comment by wardseptember** [comment]
@qq781261148 使用oracle jdk 8部分单测也可能报错，因为trpc-java支持tencent jdk 8 的协程，如果你想编译开发可以安装https://github.com/Tencent/TencentKona-8/releases/tag/Fiber-8.0.13-GA   Tencent Kona jdk 8 fiber版本。
如果你不想安装，可以试试跳过单测，`mvn clean install '-Dmaven.test.skip=true'`
